### PR TITLE
Change gradle docker plugin

### PR DESCRIPTION
**Pull request by geoand**
This PR is a result of the discussion on issue #25.

I tried to make the least changes possible while changing the plugin

I'm looking forward to your feedback,
George

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@geoand Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-spring-boot-docker&pullRequestId=26)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-spring-boot-docker&pullRequestId=26) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@geoand Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-spring-boot-docker&pullRequestId=26)!

**Comment by geoand** [comment]
I rebased the PR on to the latest master

**Comment by dsyer** [comment]
I think this is obsolete since we switched to jib.

**Pull request closed without merging**
