### PR TITLE
Run application with user privileges

### PR DESCRIPTION
**Pull request by VonUniGE**
Implement the good practice to not run applications with root privileges.
See https://github.com/spring-guides/gs-spring-boot-docker/issues/56

### CODE REVIEW

**Comment by dsyer** [comment]
Good idea. However, I would prefer to introduce it as a separate step, explaining in the text why we do it. (Also there are conflicts, so a rebase is needed.) Do you want to do that?

**Comment by dsyer** [comment]
Thanks for the help rebasing. I can merge this but it isn't finished. Are you still working on it?

**Comment by VonUniGE** [comment]
Rebased.
Some pointers about why this is useful:
 - [Can a root user inside a Docker/LXC break the security of the whole system?](https://security.stackexchange.com/questions/106860/can-a-root-user-inside-a-docker-lxc-break-the-security-of-the-whole-system)
 - [Processes In Containers Should Not Run As Root](https://medium.com/@mccode/processes-in-containers-should-not-run-as-root-2feae3f0df3b) 
 - [Do Not Run Dockerized Applications as Root](https://americanexpress.io/do-not-run-dockerized-applications-as-root/)

**Comment by VonUniGE** [comment]
Yes, you can merge this. The explanation in the guide can be added in another PR.

**Comment by dsyer** [comment]
Thanks. I'd prefer to fix it here if you are still working on it. That way we can split the change in the `Dockerfile` into a new paragraph or section, and explain it properly. So if you are still working on it, I'll just wait.

**Pull request merged**
