### PR TITLE
Update README.adoc

### PR DESCRIPTION
**Pull request by virmundi**
Order of plugins affects which jar artifact gets into the image.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@virmundi Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-spring-boot-docker&pullRequestId=54)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-spring-boot-docker&pullRequestId=54) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@virmundi Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-spring-boot-docker&pullRequestId=54)!

**Comment by dsyer** [comment]
> If the docker image contains the pre-shaded jar, you need to explicitly declare the  spring-boot-maven-plugin before the docker plugin declaration.

Not much detail there. What happens if you get it wrong? How does the code in this project prevent it from going wrong? Isn't "shaded" the wrong adjective for a Spring Boot ueberjar anyway?

**Comment by virmundi** [comment]
I've added some more detail.

**Comment by dsyer** [comment]
I see. How about just pointing out that the order is important and refer to the "complete" sample for details? E.g.

> The order of plugins matters in the `pom.xml`: note that in the "complete" sample, the docker plugin appears below the Spring Boot plugin. This ensures that the jar file is available and fully enhanced at the time that the docker plugin runs.

**Comment by virmundi** [comment]
That would be fine too.

**Comment by dsyer** [comment]
I think this is obsolete (we aren't using the docker plugin any more).

**Pull request closed without merging**
