### PR TITLE
ISSUE-90 // zsh: no matches found: JAR_FILE=build/libs/*.jar #90

### PR DESCRIPTION
**Pull request by Raghav2211**
1. Use escape character in docker build command for gradle
2. update README.adoc

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Raghav2211 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-spring-boot-docker&pullRequestId=91)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-spring-boot-docker&pullRequestId=91) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Raghav2211 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-spring-boot-docker&pullRequestId=91)!

**Comment by dsyer** [comment]
I think the unescaped “*” was intentional. If the jar file isn’t there it won’t work though (and neither will the escaped variant). Are you sure you ran `gradle build` first?

**Comment by Raghav2211** [comment]
> I think the unescaped “*” was intentional. If the jar file isn’t there it won’t work though (and neither will the escaped variant). Are you sure you ran `gradle build` first?

Yup i ran build first with /bin/zsh and then build docker image and if the file is not exists then `COPY` command throw error 
`COPY failed: no source files were specified`
Although in bash it's working fine but with zsh it throw error and WIK zsh has default behaviour when it comes to failed globbing

**Comment by dsyer** [comment]
But the file *does* exist, doesn’t it (if you run `gradle build` first)? So what’s the problem?

**Comment by Raghav2211** [comment]
> But the file _does_ exist, doesn’t it (if you run `gradle build` first)? So what’s the problem?

if the file also exist even then it throw error in docker gradle build
`zsh: no matches found: JAR_FILE=build/libs/*.jar`

**Comment by Raghav2211** [comment]
@dsyer Please review & let me know

**Comment by dsyer** [comment]
I guess if it works for you it must be OK.

**Pull request merged**
