### PR TITLE
Update plugin docker-maven-plugin to 0.4.11

### PR DESCRIPTION
**Pull request by borisroman**
This allows the project to build with a Docker for Mac setup.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@borisroman Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-spring-boot-docker&pullRequestId=20)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-spring-boot-docker&pullRequestId=20) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/faq) for frequently asked questions.

**Comment by gregturn** [comment]
What is the state of docker for Mac?

**Comment by borisroman** [comment]
@gregturn Works pretty well I must say. It's been marked as stable since the end of July: https://docs.docker.com/docker-for-mac/release-notes/

**Comment by gregturn** [comment]
@borisroman if you're willing to update the branch we can merge this.

**Comment by pivotal-issuemaster** [comment]
@borisroman Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-spring-boot-docker&pullRequestId=20)!

**Comment by gregturn** [comment]
Thanks!

**Pull request merged**
