### PR TITLE
Removed $ from copyable commands

### PR DESCRIPTION
**Pull request by mohamedanees6**
Removed $ from all the copyable commands since this is causing issues while pasting them on terminal

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@mohamedanees6 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-spring-boot-docker&pullRequestId=78)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-spring-boot-docker&pullRequestId=78) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by mohamedanees6** [comment]
@pivotal-issuemaster This is an Obvious Fix

**Comment by pivotal-issuemaster** [comment]
@mohamedanees6 This Pull Request contains an obvious fix. Signing the Contributor License Agreement is not necessary.

**Comment by dsyer** [comment]
It's not 100% obvious that this is the right thing to do. There's no visual signal that the text is a command line, and not the output of one, or a file contents, without the "$". I'm certainly open to suggestion about how to make tings work better, but I'm not keen to just delete them and not replace with some other feature (like some javascript to do the copy, perhaps?).

**Comment by dsyer** [comment]
Maybe @BoykoAlex would have something to contribute?

**Comment by dsyer** [comment]
Superseded by b966ba1. Thanks for the patch.

**Pull request closed without merging**
