### PR TITLE
support JAVA_OPTS  and docker stop SIGTERM

### PR DESCRIPTION
**Pull request by An0nymous0**
1.support JAVA_OPTS
    docker run -e "JAVA_OPTS=-Dserver.port=8080"
2.docker stop send SIGTERM signal

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@An0nymous0 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-spring-boot-docker&pullRequestId=55)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-spring-boot-docker&pullRequestId=55) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@An0nymous0 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-spring-boot-docker&pullRequestId=55)!

**Comment by matthiasbalke** [comment]
I stumbled above the same error, within the documentation. But the fix is rather simple.
Instead of using `JAVA_OPTS` you have to use `JAVA_TOOL_OPTIONS` and do not change anything at all inside the `Dockerfile`.

Here is a link to the Oracle documentation for this environment variable: https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/envvars002.html

Just use it like this:
```sh
docker run \
  -p 8080:8080 \
  -p 5005:5005 \
  --env JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n \
  -t springio/gs-spring-boot-docker
```

**Comment by dsyer** [comment]
Exposing JAVA_OPTS and handling signals is covered in the more complete [topical guide](https://github.com/spring-guides/top-spring-boot-docker). Also the `Dockerfile` we have already supports SIGTERM (works for me anyway). There is a link in this guide, so I'd rather leave it at that really (this is about "getting started" - we don't want to do too much).

**Pull request closed without merging**
