### PR TITLE
LICENSE correction

### PR DESCRIPTION
**Pull request by eaccmk**
- Added complete `Apache LICENSE v2.0` see new file `LICENSE`
- Added reference to LICENSE in `Readme` file

Note: I have moved the `   Copyright 2013 GoPivotal` to actual position as per `LICENSE` format alike any other legal doc.

This small piece of work is an attempt to contribute back to the community. Thank you !

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@eaccmk Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-spring-boot-docker&pullRequestId=85)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-spring-boot-docker&pullRequestId=85) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@eaccmk Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-spring-boot-docker&pullRequestId=85)!

**Comment by eaccmk** [comment]
@pivotal-issuemaster This is an Obvious Fix

**Comment by dsyer** [comment]
Thanks for alerting us to the possibility of having Github detect the license. Superceded by 38ab7cb126adb37f036403d416a009995623bd96. Still work in progress.

**Pull request closed without merging**
